### ISSUE TITLE
docker aio errors - mysql not getting populated

### ISSUE THREAD

**Issue by devpets** [OpenBMP/docker#1]
Ubuntu 14.04, deployed via docker instructions in Readme.md file,

openbmp.log:
2016-01-22T22:07:56.156179 | ERROR    | send_bmp_raw       | rtr=X.X.X.X: Failed to produce bmp raw message: Local: Queue full
2016-01-22T22:08:00.140914 | ERROR    | produce            | rtr=X.X.X.X: Failed to produce message: Local: Queue full
2016-01-22T22:08:00.140943 | ERROR    | produce            | rtr=X.X.X.X: Failed to produce message: Local: Queue full
2016-01-22T22:08:00.140952 | ERROR    | send_bmp_raw       | rtr=X.X.X.X: Failed to produce bmp raw message: Local: Queue full
2016-01-22T22:08:01.189515 | ERROR    | produce            | rtr=X.X.X.X: Failed to produce message: Local: Queue full
2016-01-22T22:08:01.189544 | ERROR    | produce            | rtr=X.X.X.X: Failed to produce message: Local: Queue full
2016-01-22T22:08:01.189554 | ERROR    | send_bmp_raw       | rtr=X.X.X.X: Failed to produce bmp raw message: Local: Queue full
2016-01-22T22:08:01.190859 | ERROR    | produce            | rtr=X.X.X.X: Failed to produce message: Local: Queue full
2016-01-22T22:08:01.190879 | ERROR    | produce            | rtr=X.X.X.X: Failed to produce message: Local: Queue full
2016-01-22T22:08:01.190886 | ERROR    | send_bmp_raw       | rtr=X.X.X.X: Failed to produce bmp raw message: Local: Queue full

tomcat logs:
root@7dae2c3346b1:/var/log/tomcat7# tail *log
==> catalina.2016-01-19.log <==
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:372)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.connect(MySQLProtocol.java:673)
        ... 35 more

Jan 19, 2016 8:01:25 PM org.apache.catalina.core.NamingContextListener addResource
WARNING: Failed to register in JMX: javax.naming.NamingException: Could not connect to localhost:3306 : Connection refused

==> catalina.2016-01-22.log <==
Jan 22, 2016 10:03:32 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Jan 22, 2016 10:03:32 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/db_rest
Jan 22, 2016 10:03:36 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /var/lib/tomcat7/webapps/ROOT
Jan 22, 2016 10:03:36 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8001"]
Jan 22, 2016 10:03:36 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 4194 ms

==> localhost.2016-01-19.log <==

==> localhost.2016-01-22.log <==

mysql default root password not working ("OpenBMP"). mysql user openbmp with pass openbmp - indeed does works. No data in tables.

Juniper routers sending data.

**Comment by devpets** [comment]
ERROR: Failed to create trigger - 1235 (42000): This version of MariaDB doesn't yet support 'multiple triggers with the same action time and event for one table'
Origin Query took 0.019655942916870117 seconds
Transit ASN list Query took 0.009265899658203125 seconds, total rows 0
RECORD_DICT length = 0
No records, skipping update
root@7dae2c3346b1:/var/log#

**Comment by devpets** [comment]
[2016-01-22 22:03:32,437] INFO Logs loading complete. (kafka.log.LogManager)
[2016-01-22 22:03:32,442] INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager)
[2016-01-22 22:03:32,450] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2016-01-22 22:03:32,503] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
[2016-01-22 22:03:32,505] INFO [Socket Server on Broker 0], Started (kafka.network.SocketServer)
[2016-01-22 22:03:32,620] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
[2016-01-22 22:03:32,664] INFO 0 successfully elected as leader (kafka.server.ZookeeperLeaderElector)
[2016-01-22 22:03:33,762] INFO New leader is 0 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
[2016-01-22 22:03:33,763] INFO Registered broker 0 at path /brokers/ids/0 with address jumbo-ubuntu:9092. (kafka.utils.ZkUtils$)
[2016-01-22 22:03:33,798] INFO [Kafka Server 0], started (kafka.server.KafkaServer)
root@7dae2c3346b1:/var/log# ls

**Comment by TimEvens** [comment]
Appears mysql didn't start.  This was a common start issue when '-e MEM=value' was larger than available memory.  A change was added to force the container to exit with an error if available memory less than MEM=value.  Can you provide the output of: docker exec openbmp_aio grep -i mysql /var/log/syslog

**Comment by TimEvens** [comment]
Closing for now since I haven't heard back and I believe this was related to the memory ENV setting.

**Comment by devpets** [comment]
docker exec openbmp_aio grep -i mysql /var/log/syslog 
empty

 Failed to produce bmp raw message: Local: Queue full

**Comment by TimEvens** [comment]
@devpets , can you run the following to see if you see the collector messages.  

```
docker exec openbmp_aio /usr/local/kafka/bin/kafka-console-consumer.sh --new-consumer --bootstrap-server localhost:9092 --from-beginning --topic openbmp.parsed.collector
```

Memory shouldn't be the issue.   The error that you have with the queue being full normally suggests that messages are not being produced to Kafka.  Based on your docker run command you are using the default API_FQDN, which is the docker hostname.    This should be working from within the container.    

Another issue is that depending on your container install/disk driver, it might have a limit.   The latest container changes the location of where Kafka is so that Kafka doesn't fill up.

**Comment by TimEvens** [comment]
closing due to inactivity.

**Comment by dgedia** [comment]
I am facing the same error as well on the collector docker container. Please suggest if there is a fix for this issue?
