### ISSUE TITLE
java exception

### ISSUE THREAD

**Issue by perimore** [OpenBMP/docker#7]
On starting the openbmp container, I get the following error. Should this be of concern?

```[ERROR] [11/16/2016 11:55:21.808] [default-akka.actor.default-dispatcher-8] [TaskInvocation] Error executing statement at line 5: CALL DROP_TABLE_IF_EXISTS('RETRIEVED_OBJECTS')
com.googlecode.flyway.core.command.FlywaySqlScriptException: Error executing statement at line 5: CALL DROP_TABLE_IF_EXISTS('RETRIEVED_OBJECTS')
       	at com.googlecode.flyway.core.dbsupport.SqlScript.execute(SqlScript.java:92)
       	at com.googlecode.flyway.core.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:72)
       	at com.googlecode.flyway.core.command.DbMigrate$2.doInTransaction(DbMigrate.java:243)
       	at com.googlecode.flyway.core.command.DbMigrate$2.doInTransaction(DbMigrate.java:241)
       	at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
       	at com.googlecode.flyway.core.command.DbMigrate.applyMigration(DbMigrate.java:241)
       	at com.googlecode.flyway.core.command.DbMigrate.access$700(DbMigrate.java:44)
       	at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:186)
       	at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:135)
       	at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
       	at com.googlecode.flyway.core.command.DbMigrate.migrate(DbMigrate.java:135)
       	at com.googlecode.flyway.core.Flyway$1.execute(Flyway.java:872)
       	at com.googlecode.flyway.core.Flyway$1.execute(Flyway.java:819)
       	at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1200)
       	at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
       	at net.ripe.rpki.validator.store.DataSources$.net$ripe$rpki$validator$store$DataSources$$migrate(DataSources.scala:87)
       	at net.ripe.rpki.validator.store.DataSources$DSSingletons$$anonfun$$init$$1.apply(DataSources.scala:47)
       	at net.ripe.rpki.validator.store.DataSources$DSSingletons$$anonfun$$init$$1.apply(DataSources.scala:43)
       	at net.ripe.rpki.validator.store.SimpleSingletons.apply(Storage.scala:80)
       	at net.ripe.rpki.validator.store.DataSources$.DurableDataSource(DataSources.scala:54)
       	at net.ripe.rpki.validator.store.DurableCaches$$anonfun$$init$$1.apply(CacheStore.scala:230)
       	at net.ripe.rpki.validator.store.DurableCaches$$anonfun$$init$$1.apply(CacheStore.scala:229)
       	at net.ripe.rpki.validator.store.SimpleSingletons.apply(Storage.scala:80)
       	at net.ripe.rpki.validator.store.DurableCaches$.apply(CacheStore.scala:232)
       	at net.ripe.rpki.validator.config.Main.net$ripe$rpki$validator$config$Main$$runValidator(Main.scala:171)
       	at net.ripe.rpki.validator.config.Main.net$ripe$rpki$validator$config$Main$$runValidator(Main.scala:162)
       	at net.ripe.rpki.validator.config.Main$$anonfun$1.apply$mcV$sp(Main.scala:135)
       	at akka.actor.DefaultScheduler$$anon$4.run(Scheduler.scala:161)
       	at akka.actor.DefaultScheduler$$anon$2$$anon$5.run(Scheduler.scala:172)
       	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:137)
       	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.sql.SQLSyntaxErrorException: The class 'net.ripe.rpki.validator.StoredProcedures' does not exist or is inaccessible. This can happen if the class is not public.
       	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
       	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
       	at org.apache.derby.impl.jdbc.Util.seeNextException(Unknown Source)
       	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
       	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
       	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
       	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
       	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
       	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)
       	at com.googlecode.flyway.core.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:230)
       	at com.googlecode.flyway.core.dbsupport.SqlScript.execute(SqlScript.java:90)
       	... 34 more
Caused by: ERROR 42X51: The class 'net.ripe.rpki.validator.StoredProcedures' does not exist or is inaccessible. This can happen if the class is not public.
       	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
       	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
       	... 45 more
Caused by: java.lang.ClassNotFoundException: net.ripe.rpki.validator.StoredProcedures : net/ripe/rpki/validator/StoredProcedures : Unsupported major.minor version 52.0
       	at org.apache.derby.impl.services.reflect.DatabaseClasses.loadApplicationClass(Unknown Source)
       	at org.apache.derby.iapi.services.loader.ClassInspector.getClass(Unknown Source)
       	at org.apache.derby.iapi.services.loader.ClassInspector.accessible(Unknown Source)
       	at org.apache.derby.impl.sql.compile.QueryTreeNode.verifyClassExist(Unknown Source)
       	at org.apache.derby.impl.sql.compile.StaticMethodCallNode.bindExpressionMinion(Unknown Source)
       	at org.apache.derby.impl.sql.compile.StaticMethodCallNode.bindExpression(Unknown Source)
       	at org.apache.derby.impl.sql.compile.JavaToSQLValueNode.bindExpression(Unknown Source)
       	at org.apache.derby.impl.sql.compile.CallStatementNode.bindStatement(Unknown Source)
       	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
       	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
       	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
       	... 38 more```

**Comment by TimEvens** [comment]
Did you recently pull/run the aio?  Yesterday, we upgraded RPKIvalidator from 2.22 to 2.23 but noticed today it was throwing those exceptions.   This was only affecting rpki validayor process. The aio container has been reverted back to rpki validator.   Can you upgrade your container to the latest?

**Comment by perimore** [comment]
It's working now. Thanks.

How do I define a router that only supports passive connections? I can see the isPassive flag in the routers table and I tried to manually define a device but it doesn't try to connect to the router. Is this possible via the API??

**Comment by TimEvens** [comment]
It's always passive, but will be active once we add making connections.  AFAIK, only JunOS supports active mode.   Do you have other implementations that accept connections?

**Comment by TimEvens** [comment]
closing this since we have the active mode question/issue tracked in openbmp repo.
